// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api from "./routes/api.tsx";
import * as $api_feedback from "./routes/api/feedback.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_stats from "./routes/api/stats.ts";
import * as $feedback from "./routes/feedback.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $API from "./islands/API.tsx";
import * as $Code from "./islands/Code.tsx";
import * as $Converter from "./islands/Converter.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FeedbackForm from "./islands/FeedbackForm.tsx";
import * as $FileItem from "./islands/FileItem.tsx";
import * as $Form from "./islands/Form.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api.tsx": $api,
    "./routes/api/feedback.ts": $api_feedback,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/stats.ts": $api_stats,
    "./routes/feedback.tsx": $feedback,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/API.tsx": $API,
    "./islands/Code.tsx": $Code,
    "./islands/Converter.tsx": $Converter,
    "./islands/Counter.tsx": $Counter,
    "./islands/FeedbackForm.tsx": $FeedbackForm,
    "./islands/FileItem.tsx": $FileItem,
    "./islands/Form.tsx": $Form,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
